FROM python:3.9.19-alpine AS builder

WORKDIR /app

RUN apk add --no-cache build-base python3-dev

COPY requirements.txt .

RUN pip install --index-url http://devpi-helm-devpi:3141/root/pypi/+simple/ \
                --trusted-host devpi-helm-devpi \
                --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.9.19-alpine

WORKDIR /app

RUN apk add --no-cache shadow-uidgid && \
    addgroup -g 3000 app && adduser -u 10001 -G app -D app

COPY --from=builder /install /usr/local

COPY src /app/src

ENV PYTHONPATH=/app/src

USER app

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]