FROM python:3.9-slim

WORKDIR /app

RUN groupadd -g 3000 app && useradd -m -u 10001 -g 3000 --no-log-init app

COPY requirements.txt .
COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

COPY src /app/src
COPY tests /app/tests

ENV PYTHONPATH=/app/src

RUN chown -R app:app /app
USER app

CMD ["sh", "-c", "PYTHONPATH=/app/src pytest --emoji -v --color=yes"]